services:
  php82:
    container_name: yokai-batch-php82
    environment:
      PHP_XDEBUG: 1
    extends:
      file: ~/.led/docker-base.yaml
      service: localuser
    hostname: php81
    image: ledup/php:8.2
    volumes:
      - .:/src
    working_dir: /src
  php81:
    container_name: yokai-batch-php81
    environment:
      PHP_XDEBUG: 1
    extends:
      file: ~/.led/docker-base.yaml
      service: localuser
    hostname: php81
    image: ledup/php:8.1
    volumes:
      - .:/src
    working_dir: /src
  php80:
    container_name: yokai-batch-php80
    environment:
      PHP_XDEBUG: 1
    extends:
      file: ~/.led/docker-base.yaml
      service: localuser
    hostname: php80
    image: ledup/php:8.0
    volumes:
      - .:/src
    working_dir: /src
  php74:
    container_name: yokai-batch-php74
    environment:
      PHP_XDEBUG: 1
    extends:
      file: ~/.led/docker-base.yaml
      service: localuser
    hostname: php74
    image: ledup/php:7.4
    volumes:
    - .:/src
    working_dir: /src
version: '2'
