services:
  php84:
    container_name: yokai-batch-php84
    extends:
      file: $HOME/.led/docker-base.yaml
      service: localuser
    hostname: php84
    image: ledup/php:8.4-rl9
    volumes:
      - .:/src
    working_dir: /src
  php83:
    container_name: yokai-batch-php83
    extends:
      file: $HOME/.led/docker-base.yaml
      service: localuser
    hostname: php83
    image: ledup/php:8.3-rl9
    volumes:
      - .:/src
    working_dir: /src
  php82:
    container_name: yokai-batch-php82
    extends:
      file: $HOME/.led/docker-base.yaml
      service: localuser
    hostname: php82
    image: ledup/php:8.2-rl9
    volumes:
      - .:/src
    working_dir: /src
  php81:
    container_name: yokai-batch-php81
    extends:
      file: $HOME/.led/docker-base.yaml
      service: localuser
    hostname: php81
    image: ledup/php:8.1-rl9
    volumes:
      - .:/src
    working_dir: /src
version: '2'
