name: Prepare env & install dependencies

on:
  workflow_call:
    inputs:
      php-version:
        required: true
        type: string
      symfony-version:
        required: true
        type: string
      coverage-mode:
        required: false
        type: string
        default: 'none'
    secrets:
      token:
        required: true

runs:
  using: "composite"
  runs-on: ubuntu-latest
  steps:
    - name: "Setup PHP"
      uses: shivammathur/setup-php@v2
      with:
        coverage: ${{ inputs.coverage-mode }}
        php-version: ${{ inputs.php-version }}
    - name: "Install dependencies with composer"
      run: |
        composer require --quiet --no-update "symfony/console:${{ inputs.symfony-version }}"
        composer require --quiet --no-update "symfony/filesystem:${{ inputs.symfony-version }}"
        composer require --quiet --no-update "symfony/framework-bundle:${{ inputs.symfony-version }}"
        composer require --quiet --no-update "symfony/messenger:${{ inputs.symfony-version }}"
        composer require --quiet --no-update "symfony/process:${{ inputs.symfony-version }}"
        composer require --quiet --no-update "symfony/serializer:${{ inputs.symfony-version }}"
        composer require --quiet --no-update "symfony/validator:${{ inputs.symfony-version }}"
        composer update --no-interaction --no-progress --no-suggest
