name: 'Packages Split'

on:
  push:
    branches:
      - 0.x
  release:
    types: [ published ]

jobs:
  packages_split:
    name: "Packages Split"
    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout"
        run: git clone https://github.com/yokai-php/batch-src /home/runner/work/yokai-php/batch-src && cd $_

      - name: "Gitsplit"
        run: docker run --rm -t -e GH_TOKEN -v /cache/gitsplit:/cache/gitsplit -v /home/runner/work/yokai-php/batch-src:/srv jderusse/gitsplit gitsplit
        env:
          GH_TOKEN: ${{ secrets.GITSPLIT_TOKEN }}
