name: "Tests"

on:
  pull_request:
  push:
    branches:
      - "0.x"

jobs:
  phpunit:
    name: "PHPUnit"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - php-version: '8.0'
            symfony-version: '5.4.*'
          - php-version: '8.0'
            symfony-version: '6.0.*'
          - php-version: '8.2'
            symfony-version: '5.4.*'
          - php-version: '8.2'
            symfony-version: '6.2.*'
          - php-version: '8.2'
            symfony-version: '7.0.*'
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
      - name: "Setup env & install dependencies"
        uses: ./.github/actions/install
        with:
          php-version: ${{ matrix.php-version }}
          symfony-version: ${{ matrix.symfony-version }}
      - name: "Run tests with phpunit/phpunit"
        run: vendor/bin/phpunit --testsuite=Code

  phpstan:
    name: "PhpStan"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
      - name: "Setup env & install dependencies"
        uses: ./.github/actions/install
        with:
          php-version: '8.2'
          symfony-version: '7.0.*'
      - name: "Run static analyzis with phpstan/phpstan"
        run: vendor/bin/phpstan analyze

  checkstyke:
    name: "Checkstyle"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
      - name: "Setup env & install dependencies"
        uses: ./.github/actions/install
        with:
          php-version: '8.2'
          symfony-version: '7.0.*'
      - name: "Run checkstyle with symplify/easy-coding-standard"
        run: vendor/bin/ecs

  conventions:
    name: "Conventions"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
      - name: "Setup env & install dependencies"
        uses: ./.github/actions/install
        with:
          php-version: '8.2'
          symfony-version: '7.0.*'
      - name: "Run tests with phpunit/phpunit"
        run: vendor/bin/phpunit --testsuite=Convention

  codecov:
    name: "Code coverage"
    needs: [phpunit, phpstan, checkstyke, conventions]
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
      - name: "Setup env & install dependencies"
        uses: ./.github/actions/install
        with:
          php-version: '8.2'
          symfony-version: '7.0.*'
          coverage-mode: 'xdebug'
      - name: "Run tests with phpunit/phpunit"
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: |
          vendor/bin/phpunit --testsuite=Code --coverage-clover coverage.xml
      - name: "Upload coverage to Codecov"
        uses: codecov/codecov-action@v1
